'use strict';
// Marzipano single-equirect viewer (Phase 0/1: menu-list navigation, no tiles).
// Reads window.APP_DATA (see data.js, generated by src/generator/build-data.js).
(function () {
  var Marzipano = window.Marzipano;
  var data = window.APP_DATA;

  var panoEl = document.querySelector('#pano');
  var viewer = new Marzipano.Viewer(panoEl, {
    controls: { mouseViewMode: (data.settings && data.settings.mouseViewMode) || 'drag' }
  });

  var MAX_FOV = 100 * Math.PI / 180;

  var scenes = data.scenes.map(function (sd) {
    var source = Marzipano.ImageUrlSource.fromString(sd.equirectUrl);
    var geometry = new Marzipano.EquirectGeometry([{ width: sd.equirectWidth || 4000 }]);
    var limiter = Marzipano.RectilinearView.limit.traditional(sd.equirectWidth || 4000, MAX_FOV);
    var view = new Marzipano.RectilinearView(sd.initialViewParameters, limiter);
    var scene = viewer.createScene({ source: source, geometry: geometry, view: view });
    return { data: sd, scene: scene, view: view };
  });

  var listEl = document.querySelector('#sceneList');
  var titleEl = document.querySelector('#titleText');
  var toggleEl = document.querySelector('#menuToggle');

  function switchTo(s) {
    s.view.setParameters(s.data.initialViewParameters);
    s.scene.switchTo();
    titleEl.textContent = s.data.name;
    Array.prototype.forEach.call(listEl.children, function (btn) {
      btn.classList.toggle('active', btn.dataset.id === s.data.id);
    });
  }

  scenes.forEach(function (s) {
    var btn = document.createElement('button');
    btn.className = 'scene-item';
    btn.textContent = s.data.name;
    btn.dataset.id = s.data.id;
    btn.addEventListener('click', function () {
      switchTo(s);
      listEl.classList.add('hidden');
    });
    listEl.appendChild(btn);
  });

  toggleEl.addEventListener('click', function () {
    listEl.classList.toggle('hidden');
  });

  if (data.settings && data.settings.autorotateEnabled) {
    var autorotate = Marzipano.autorotate({ yawSpeed: 0.03, targetPitch: 0, targetFov: Math.PI / 2 });
    viewer.setIdleMovement(3000, autorotate);
  }

  if (scenes.length) switchTo(scenes[0]);
})();
