'use strict';
/*
 * build-data.js — генерирует Marzipano `data.js` (объект APP_DATA) из manifest.json.
 *
 * Phase 0/1: single-equirect (одна картинка на сцену, без тайлов), пустые хотспоты,
 * навигация меню-списком. Углы — В РАДИАНАХ (см. CLAUDE.md §7).
 *
 *   node src/generator/build-data.js \
 *     --manifest input/manifest.json \
 *     --images   input/ \
 *     --out      work/data.js
 *
 * Пути картинок в data.js указываются как `img/<file>` — assemble кладёт панорамы
 * в <output>/img/.
 */
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) args[a.slice(2)] = argv[++i];
  }
  return args;
}

const DEG = Math.PI / 180;
const DEFAULT_FOV = 90 * DEG; // радианы

async function main() {
  const args = parseArgs(process.argv);
  const manifestPath = args.manifest || 'input/manifest.json';
  const imagesDir = args.images || path.dirname(manifestPath);
  const outPath = args.out || 'work/data.js';

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  // Порядок: по order, затем по имени файла (MVP без приложения — §6).
  const scenesIn = (manifest.scenes || [])
    .slice()
    .sort((a, b) => (a.order ?? 1e9) - (b.order ?? 1e9) || String(a.file).localeCompare(String(b.file)));

  const scenes = [];
  for (const s of scenesIn) {
    if (s.quality && s.quality.status === 'reject') {
      console.warn(`skip (reject): ${s.id}`);
      continue;
    }
    const file = s.file || `${s.id}.jpg`;
    const imgPath = path.join(imagesDir, file);
    let width = 4000;
    try {
      const meta = await sharp(imgPath).metadata();
      if (meta.width) width = meta.width;
      if (meta.width && meta.height && Math.abs(meta.width / meta.height - 2) > 0.02) {
        console.warn(`warn: ${file} не 2:1 (${meta.width}x${meta.height}) — equirect ждёт 2:1`);
      }
    } catch (e) {
      console.warn(`warn: не прочитать ${imgPath} (${e.message}) — width=${width}`);
    }

    scenes.push({
      id: s.id,
      name: s.name || s.id,
      equirectUrl: `img/${file}`,
      equirectWidth: width,
      initialViewParameters: { yaw: 0, pitch: 0, fov: DEFAULT_FOV },
      linkHotspots: [],
      infoHotspots: []
    });
  }

  const appData = {
    scenes,
    name: (manifest.tour && manifest.tour.name) || 'Tour',
    settings: {
      autorotateEnabled: !!(manifest.settings && manifest.settings.autorotate),
      mouseViewMode: 'drag'
    }
  };

  const banner = '// GENERATED by src/generator/build-data.js — не редактировать вручную.\n';
  const body = `var APP_DATA = ${JSON.stringify(appData, null, 2)};\n`;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, banner + body);
  console.log(`wrote ${outPath} — ${scenes.length} scene(s)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
